amp_replace.settings:
  type: mapping
  label: 'AMP Replace settings'
  mapping:
    amp_library_process_full_html:
      type: boolean
      label: 'If the full html should be processed by the AMP library'
    amp_library_process_full_html_warnings:
      type: boolean
      label: 'Whether to add a notice in the Drupal log for each AMP page showing AMP warnings'
    amp_library_process_statistics:
      type: boolean
      label: 'Whether to add an HTML comment with statistics to the Drupal page output'
