amp.settings:
  type: mapping
  label: 'AMP settings'
  mapping:
    langcode:
      type: string
    google_analytics_id:
      type: string
      label: 'Google Analytics Web Property ID'
    google_doubleclick_id:
      type: string
      label: 'Google DoubleClick for Publishers Network ID'
    amp_pixel:
      type: boolean
      label: 'Whether the amp-pixel should be included'
    amp_pixel_domain_name:
      type: string
      label: 'Domain name of tracking pixel'
    amp_pixel_query_string:
      type: string
      label: 'Query path for domain of tracking pixel'
    amp_pixel_random_number:
      type: boolean
      label: 'Whether to include a random number in the URL'
    amp_everywhere:
      type: boolean
      label: 'Generate all pages as AMP pages?'
    process_full_html:
      type: string
      label: 'Process the whole page through the AMP converter.'

