amp.settings:
  type: mapping
  label: 'AMP settings'
  mapping:
    langcode:
      type: string
    amp_everywhere:
      type: boolean
      label: 'Generate all pages as AMP pages?'
    process_full_html:
      type: string
      label: 'Process the whole page through the AMP converter.'

